site: Pratik Nilange
url: https://pratiknilange.in #yoururl
title: Pratik Nilange
description: tech, design, and lame jokes.
twitter:
  username: pnonf #yourusername
  card: summary
  creator: pnonf #yourusername
author:
  twitter: pnonf #yourusername
  name: pnonf #yourusername
  avatar:
  email: #youremail
  url: pratiknilange.in #yoururl
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"