# Example Site settings

#google_analytics: UA-NNNNNNNN-N

title: Pratik Nilange

url: https://pratiknilange.in

header_pages:
  - index.md
  - about.md
  - work.md

footer: 'bad puns on <a target="_blank" href="https://twitter.com/pnonf">twitter</a>'

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag