# site
title: Pratik Nilange
baseurl: ""
url: "https://pratiknilange.in"
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: Pratik Nilange
desc: >
  Unlucky in cards

# posts
# date_format: "%Y"
post_title: Story
post_date: Date
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock